import type { CanonicalBytes } from './contexts';
import { bytesEqual } from './encoding';
import { CryptoError, CryptoErrorCode } from './errors';
import { ecdsaVerifyRaw } from './internal/raw';
import { ECDSA } from './params';
import { algorithmOf, type Bytes, type Key, type KeyPair } from './types';
import { guarded, subtle } from './webcrypto';

/**
 * ECDSA on P-256 with SHA-256 (CP-26, ADR-015), the identity's signing key. It signs only
 * canonical statements built by contexts.ts (binding, vault re-wrap, and from Phase 6 room
 * statements); it never encrypts or wraps anything. The per-signature nonce is generated by the
 * platform's cryptographic library, not by CipherMesh. Signatures use the IEEE P1363 encoding
 * (r || s, 64 bytes) that WebCrypto produces. Signatures are never used as identifiers, so ECDSA
 * malleability (s and n - s both verify) does not matter here.
 */
const ALGORITHM = { name: ECDSA.name, namedCurve: ECDSA.namedCurve } as const;
const SIGN = { name: ECDSA.name, hash: ECDSA.hash } as const;

/** Generates the signing key pair; the private key is extractable only to be wrapped once. */
export async function generateSigningKeyPair(): Promise<KeyPair> {
  return guarded(CryptoErrorCode.UNAVAILABLE, async () => {
    const pair = (await subtle().generateKey(ALGORITHM, true, ['sign', 'verify'])) as KeyPair;
    return pair;
  });
}

/** Imports and validates a P-256 public key; the DER must equal WebCrypto's own re-export. */
export async function importSigningPublicKey(spki: Bytes): Promise<Key> {
  if (spki.length !== ECDSA.spkiBytes) throw new CryptoError(CryptoErrorCode.IDENTITY_INVALID);
  const key = await guarded(CryptoErrorCode.IDENTITY_INVALID, () =>
    subtle().importKey('spki', spki, ALGORITHM, true, ['verify']),
  );
  const algorithm = algorithmOf(key);
  const reExported = await guarded(
    CryptoErrorCode.IDENTITY_INVALID,
    async () => new Uint8Array(await subtle().exportKey('spki', key)),
  );
  if (algorithm.name !== ECDSA.name || algorithm.namedCurve !== ECDSA.namedCurve || !bytesEqual(reExported, spki)) {
    throw new CryptoError(CryptoErrorCode.IDENTITY_INVALID);
  }
  return key;
}

/** Signs a canonical statement. */
export async function signStatement(privateKey: Key, statement: CanonicalBytes): Promise<Bytes> {
  if (statement.length === 0) throw new CryptoError(CryptoErrorCode.INVALID_INPUT);
  const signature = await guarded(
    CryptoErrorCode.INVALID_INPUT,
    async () => new Uint8Array(await subtle().sign(SIGN, privateKey, statement)),
  );
  if (signature.length !== ECDSA.signatureBytes) throw new CryptoError(CryptoErrorCode.INVALID_INPUT);
  return signature;
}

/** Verifies a signature over a canonical statement. Returns false for any failure. */
export async function verifyStatement(publicKey: Key, statement: CanonicalBytes, signature: Bytes): Promise<boolean> {
  if (statement.length === 0) return false;
  return ecdsaVerifyRaw(publicKey, statement, signature);
}
