-- CipherMesh schema v1 (CM-T013). Generated by `prisma migrate diff --from-empty` from
-- prisma/schema.prisma, plus the citext extension below. Reviewed for Phase 2.
-- CHECK constraints, triggers and grants follow in the next migrations.

-- Case-insensitive email column (data-model 4.1). citext is a trusted extension, so the
-- database owner (the migration role) can create it without superuser rights.
CREATE EXTENSION IF NOT EXISTS "citext";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "PlatformRole" AS ENUM ('USER', 'PLATFORM_ADMIN');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'DISABLED');

-- CreateEnum
CREATE TYPE "SessionRevokeReason" AS ENUM ('LOGOUT', 'REVOKED_BY_USER', 'REVOKED_BY_ADMIN', 'PASSWORD_CHANGED', 'MFA_CHANGED', 'RECOVERY_CODE_USED', 'VAULT_RESET', 'PLATFORM_ROLE_CHANGED', 'ACCOUNT_DISABLED', 'SESSION_LIMIT');

-- CreateEnum
CREATE TYPE "LoginOutcome" AS ENUM ('SUCCESS', 'BAD_CREDENTIALS', 'MFA_FAILED', 'THROTTLED', 'DISABLED');

-- CreateEnum
CREATE TYPE "KeyPairStatus" AS ENUM ('ACTIVE', 'SUPERSEDED', 'REVOKED');

-- CreateEnum
CREATE TYPE "SecurityProfile" AS ENUM ('STANDARD', 'CONFIDENTIAL', 'RESTRICTED');

-- CreateEnum
CREATE TYPE "RoomStatus" AS ENUM ('ACTIVE', 'DELETING', 'DELETED');

-- CreateEnum
CREATE TYPE "RoomKeyState" AS ENUM ('ACTIVE', 'REKEY_REQUIRED', 'REKEYING');

-- CreateEnum
CREATE TYPE "RekeyReason" AS ENUM ('MEMBER_REMOVED', 'MEMBER_LEFT', 'MEMBER_SUSPENDED', 'MEMBER_DELETED', 'IDENTITY_KEY_COMPROMISED', 'CRYPTOPERIOD_EXPIRED', 'WRAP_LIMIT_REACHED');

-- CreateEnum
CREATE TYPE "KeyVersionReason" AS ENUM ('INITIAL', 'MANUAL', 'POLICY_CHANGE', 'MEMBER_REMOVED', 'MEMBER_LEFT', 'MEMBER_SUSPENDED', 'MEMBER_DELETED', 'IDENTITY_KEY_COMPROMISED', 'CRYPTOPERIOD_EXPIRED', 'WRAP_LIMIT_REACHED');

-- CreateEnum
CREATE TYPE "RoomRole" AS ENUM ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER');

-- CreateEnum
CREATE TYPE "InvitationRole" AS ENUM ('ADMIN', 'MEMBER', 'VIEWER');

-- CreateEnum
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'REMOVED', 'LEFT');

-- CreateEnum
CREATE TYPE "RemovalReason" AS ENUM ('REMOVED_BY_ADMIN', 'LEFT_ROOM', 'ACCOUNT_DISABLED', 'ACCOUNT_DELETED');

-- CreateEnum
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING_APPROVAL', 'PENDING', 'ACCEPTED', 'DECLINED', 'REVOKED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "KeyVersionStatus" AS ENUM ('ACTIVE', 'RETIRED', 'DESTROYED');

-- CreateEnum
CREATE TYPE "RekeyMode" AS ENUM ('MANDATORY', 'MANUAL');

-- CreateEnum
CREATE TYPE "RekeyStatus" AS ENUM ('PENDING', 'COMPLETED', 'ABANDONED', 'SUPERSEDED', 'CANCELLED', 'STALE');

-- CreateEnum
CREATE TYPE "EnvelopeStatus" AS ENUM ('PENDING', 'ACTIVE');

-- CreateEnum
CREATE TYPE "FileStatus" AS ENUM ('PENDING_UPLOAD', 'AVAILABLE', 'DELETED');

-- CreateEnum
CREATE TYPE "SecretStatus" AS ENUM ('ACTIVE', 'REVEALED', 'EXPIRED', 'REVOKED');

-- CreateEnum
CREATE TYPE "AuditActorType" AS ENUM ('USER', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AuditOutcome" AS ENUM ('SUCCESS', 'DENIED', 'FAILURE');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" CITEXT NOT NULL,
    "display_name" VARCHAR(80) NOT NULL,
    "password_hash" VARCHAR(256) NOT NULL,
    "password_changed_at" TIMESTAMPTZ(3) NOT NULL,
    "platform_role" "PlatformRole" NOT NULL DEFAULT 'USER',
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "mfa_enabled" BOOLEAN NOT NULL DEFAULT false,
    "mfa_totp_secret_enc" BYTEA,
    "mfa_totp_key_id" VARCHAR(64),
    "mfa_last_used_step" BIGINT,
    "failed_login_count" INTEGER NOT NULL DEFAULT 0,
    "throttled_until" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_login_at" TIMESTAMPTZ(3),
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "recovery_codes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "code_digest" BYTEA NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "recovery_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "token_digest" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(3) NOT NULL,
    "idle_expires_at" TIMESTAMPTZ(3) NOT NULL,
    "absolute_expires_at" TIMESTAMPTZ(3) NOT NULL,
    "authenticated_at" TIMESTAMPTZ(3) NOT NULL,
    "mfa_verified_at" TIMESTAMPTZ(3),
    "step_up_at" TIMESTAMPTZ(3),
    "ip_address" INET,
    "user_agent" VARCHAR(512),
    "rotated_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),
    "revoke_reason" "SessionRevokeReason",

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "login_attempts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" UUID,
    "identifier_hmac" BYTEA,
    "ip_address" INET,
    "user_agent" VARCHAR(512),
    "outcome" "LoginOutcome" NOT NULL,

    CONSTRAINT "login_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_key_pairs" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "status" "KeyPairStatus" NOT NULL DEFAULT 'ACTIVE',
    "algorithm_suite" VARCHAR(16) NOT NULL,
    "public_key_spki" BYTEA NOT NULL,
    "public_key_fingerprint" CHAR(64) NOT NULL,
    "encrypted_private_key" BYTEA,
    "private_key_iv" BYTEA NOT NULL,
    "kdf_algorithm" VARCHAR(16) NOT NULL,
    "kdf_memory_kib" INTEGER NOT NULL,
    "kdf_iterations" INTEGER NOT NULL,
    "kdf_parallelism" INTEGER NOT NULL,
    "kdf_salt" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "superseded_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),

    CONSTRAINT "user_key_pairs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rooms" (
    "id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "security_profile" "SecurityProfile" NOT NULL,
    "policy_version" INTEGER NOT NULL,
    "current_key_version" INTEGER NOT NULL DEFAULT 1,
    "key_state" "RoomKeyState" NOT NULL DEFAULT 'ACTIVE',
    "rekey_reasons" "RekeyReason"[] DEFAULT ARRAY[]::"RekeyReason"[],
    "rekey_required_since" TIMESTAMPTZ(3),
    "membership_epoch" BIGINT NOT NULL DEFAULT 0,
    "status" "RoomStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "rooms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "room_members" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "room_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "RoomRole" NOT NULL,
    "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',
    "first_key_version" INTEGER NOT NULL,
    "added_by_id" UUID,
    "invitation_id" UUID,
    "joined_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "removed_at" TIMESTAMPTZ(3),
    "removed_by_id" UUID,
    "removal_reason" "RemovalReason",

    CONSTRAINT "room_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invitations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "room_id" UUID NOT NULL,
    "invitee_user_id" UUID NOT NULL,
    "invitee_key_id" UUID NOT NULL,
    "invited_by_id" UUID NOT NULL,
    "role" "InvitationRole" NOT NULL,
    "status" "InvitationStatus" NOT NULL,
    "approved_by_id" UUID,
    "approved_at" TIMESTAMPTZ(3),
    "confirmed_fingerprint" CHAR(64),
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "responded_at" TIMESTAMPTZ(3),

    CONSTRAINT "invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "room_key_versions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "room_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "status" "KeyVersionStatus" NOT NULL,
    "commitment" BYTEA NOT NULL,
    "algorithm_suite" VARCHAR(16) NOT NULL,
    "reasons" "KeyVersionReason"[],
    "created_by_operation_id" UUID,
    "wrap_count" INTEGER NOT NULL DEFAULT 0,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "retired_at" TIMESTAMPTZ(3),
    "destroyed_at" TIMESTAMPTZ(3),

    CONSTRAINT "room_key_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rekey_operations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "room_id" UUID NOT NULL,
    "started_by_id" UUID NOT NULL,
    "mode" "RekeyMode" NOT NULL,
    "status" "RekeyStatus" NOT NULL DEFAULT 'PENDING',
    "base_version" INTEGER NOT NULL,
    "target_version" INTEGER NOT NULL,
    "membership_epoch" BIGINT NOT NULL,
    "recipient_set_digest" BYTEA NOT NULL,
    "lease_expires_at" TIMESTAMPTZ(3) NOT NULL,
    "payload_digest" BYTEA,
    "closed_reason" VARCHAR(64),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),
    "closed_at" TIMESTAMPTZ(3),

    CONSTRAINT "rekey_operations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "key_envelopes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "room_id" UUID NOT NULL,
    "key_version" INTEGER NOT NULL,
    "recipient_user_id" UUID NOT NULL,
    "recipient_key_id" UUID NOT NULL,
    "invitation_id" UUID,
    "status" "EnvelopeStatus" NOT NULL,
    "wrapped_key" BYTEA NOT NULL,
    "algorithm" VARCHAR(32) NOT NULL,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "key_envelopes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encrypted_files" (
    "id" UUID NOT NULL,
    "room_id" UUID NOT NULL,
    "uploader_id" UUID NOT NULL,
    "key_version" INTEGER NOT NULL,
    "status" "FileStatus" NOT NULL DEFAULT 'PENDING_UPLOAD',
    "algorithm_suite" VARCHAR(16) NOT NULL,
    "wrapped_dek" BYTEA,
    "dek_iv" BYTEA NOT NULL,
    "content_iv" BYTEA NOT NULL,
    "manifest_ciphertext" BYTEA,
    "manifest_iv" BYTEA NOT NULL,
    "object_key" VARCHAR(128) NOT NULL,
    "ciphertext_size" BIGINT NOT NULL,
    "ciphertext_sha256" BYTEA NOT NULL,
    "expires_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "uploaded_at" TIMESTAMPTZ(3),
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "encrypted_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encrypted_notes" (
    "id" UUID NOT NULL,
    "room_id" UUID NOT NULL,
    "author_id" UUID NOT NULL,
    "updated_by_id" UUID NOT NULL,
    "revision" INTEGER NOT NULL,
    "key_version" INTEGER NOT NULL,
    "algorithm_suite" VARCHAR(16) NOT NULL,
    "wrapped_dek" BYTEA,
    "dek_iv" BYTEA NOT NULL,
    "ciphertext" BYTEA,
    "content_iv" BYTEA NOT NULL,
    "ciphertext_sha256" BYTEA NOT NULL,
    "expires_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "encrypted_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "secrets" (
    "id" UUID NOT NULL,
    "room_id" UUID NOT NULL,
    "sender_id" UUID NOT NULL,
    "recipient_user_id" UUID NOT NULL,
    "recipient_key_id" UUID NOT NULL,
    "status" "SecretStatus" NOT NULL DEFAULT 'ACTIVE',
    "burn_after_reading" BOOLEAN NOT NULL,
    "algorithm_suite" VARCHAR(16) NOT NULL,
    "wrapped_sek" BYTEA,
    "wrap_algorithm" VARCHAR(32) NOT NULL,
    "payload_ciphertext" BYTEA,
    "payload_iv" BYTEA,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revealed_at" TIMESTAMPTZ(3),
    "destroyed_at" TIMESTAMPTZ(3),

    CONSTRAINT "secrets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_events" (
    "seq" BIGINT NOT NULL,
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "actor_type" "AuditActorType" NOT NULL,
    "actor_user_id" UUID,
    "action" VARCHAR(64) NOT NULL,
    "outcome" "AuditOutcome" NOT NULL,
    "room_id" UUID,
    "target_type" VARCHAR(32),
    "target_id" UUID,
    "request_id" VARCHAR(64),
    "details" JSONB NOT NULL DEFAULT '{}',
    "prev_hash" BYTEA NOT NULL,
    "event_hash" BYTEA NOT NULL,
    "hash_version" INTEGER NOT NULL,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("seq")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "recovery_codes_code_digest_key" ON "recovery_codes"("code_digest");

-- CreateIndex
CREATE INDEX "recovery_codes_user_id_idx" ON "recovery_codes"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_digest_key" ON "sessions"("token_digest");

-- CreateIndex
CREATE INDEX "sessions_user_id_absolute_expires_at_idx" ON "sessions"("user_id", "absolute_expires_at");

-- CreateIndex
CREATE INDEX "sessions_absolute_expires_at_idx" ON "sessions"("absolute_expires_at");

-- CreateIndex
CREATE INDEX "login_attempts_user_id_occurred_at_idx" ON "login_attempts"("user_id", "occurred_at");

-- CreateIndex
CREATE INDEX "login_attempts_identifier_hmac_occurred_at_idx" ON "login_attempts"("identifier_hmac", "occurred_at");

-- CreateIndex
CREATE INDEX "login_attempts_occurred_at_idx" ON "login_attempts"("occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "user_key_pairs_public_key_fingerprint_key" ON "user_key_pairs"("public_key_fingerprint");

-- CreateIndex
CREATE UNIQUE INDEX "user_key_pairs_id_user_id_key" ON "user_key_pairs"("id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_key_pairs_one_active_per_user" ON "user_key_pairs"("user_id") WHERE (status = 'ACTIVE');

-- CreateIndex
CREATE INDEX "rooms_created_by_id_idx" ON "rooms"("created_by_id");

-- CreateIndex
CREATE INDEX "room_members_user_id_status_idx" ON "room_members"("user_id", "status");

-- CreateIndex
CREATE INDEX "room_members_room_id_status_idx" ON "room_members"("room_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "room_members_one_current_membership" ON "room_members"("room_id", "user_id") WHERE (status = 'ACTIVE' OR status = 'SUSPENDED');

-- CreateIndex
CREATE UNIQUE INDEX "room_members_one_active_owner" ON "room_members"("room_id") WHERE (role = 'OWNER' AND status = 'ACTIVE');

-- CreateIndex
CREATE INDEX "invitations_invitee_user_id_status_idx" ON "invitations"("invitee_user_id", "status");

-- CreateIndex
CREATE INDEX "invitations_room_id_status_idx" ON "invitations"("room_id", "status");

-- CreateIndex
CREATE INDEX "invitations_open_expiry_idx" ON "invitations"("expires_at") WHERE (status = 'PENDING_APPROVAL' OR status = 'PENDING');

-- CreateIndex
CREATE UNIQUE INDEX "invitations_id_room_id_key" ON "invitations"("id", "room_id");

-- CreateIndex
CREATE UNIQUE INDEX "invitations_one_open_per_invitee" ON "invitations"("room_id", "invitee_user_id") WHERE (status = 'PENDING_APPROVAL' OR status = 'PENDING');

-- CreateIndex
CREATE INDEX "room_key_versions_created_by_operation_id_idx" ON "room_key_versions"("created_by_operation_id");

-- CreateIndex
CREATE UNIQUE INDEX "room_key_versions_room_id_version_key" ON "room_key_versions"("room_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "room_key_versions_one_active_per_room" ON "room_key_versions"("room_id") WHERE (status = 'ACTIVE');

-- CreateIndex
CREATE INDEX "rekey_operations_pending_lease_idx" ON "rekey_operations"("lease_expires_at") WHERE (status = 'PENDING');

-- CreateIndex
CREATE INDEX "rekey_operations_closed_at_idx" ON "rekey_operations"("closed_at");

-- CreateIndex
CREATE UNIQUE INDEX "rekey_operations_id_room_id_key" ON "rekey_operations"("id", "room_id");

-- CreateIndex
CREATE UNIQUE INDEX "rekey_operations_one_pending_per_room" ON "rekey_operations"("room_id") WHERE (status = 'PENDING');

-- CreateIndex
CREATE INDEX "key_envelopes_room_id_recipient_user_id_idx" ON "key_envelopes"("room_id", "recipient_user_id");

-- CreateIndex
CREATE INDEX "key_envelopes_recipient_key_id_idx" ON "key_envelopes"("recipient_key_id");

-- CreateIndex
CREATE INDEX "key_envelopes_invitation_id_idx" ON "key_envelopes"("invitation_id");

-- CreateIndex
CREATE UNIQUE INDEX "key_envelopes_room_id_key_version_recipient_key_id_key" ON "key_envelopes"("room_id", "key_version", "recipient_key_id");

-- CreateIndex
CREATE UNIQUE INDEX "encrypted_files_object_key_key" ON "encrypted_files"("object_key");

-- CreateIndex
CREATE INDEX "encrypted_files_room_id_status_created_at_idx" ON "encrypted_files"("room_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "encrypted_files_uploader_id_idx" ON "encrypted_files"("uploader_id");

-- CreateIndex
CREATE INDEX "encrypted_files_live_expiry_idx" ON "encrypted_files"("expires_at") WHERE (status <> 'DELETED' AND expires_at IS NOT NULL);

-- CreateIndex
CREATE INDEX "encrypted_notes_room_id_updated_at_idx" ON "encrypted_notes"("room_id", "updated_at");

-- CreateIndex
CREATE INDEX "encrypted_notes_author_id_idx" ON "encrypted_notes"("author_id");

-- CreateIndex
CREATE INDEX "encrypted_notes_updated_by_id_idx" ON "encrypted_notes"("updated_by_id");

-- CreateIndex
CREATE INDEX "encrypted_notes_live_expiry_idx" ON "encrypted_notes"("expires_at") WHERE (deleted_at IS NULL AND expires_at IS NOT NULL);

-- CreateIndex
CREATE INDEX "secrets_room_id_recipient_user_id_status_idx" ON "secrets"("room_id", "recipient_user_id", "status");

-- CreateIndex
CREATE INDEX "secrets_room_id_sender_id_idx" ON "secrets"("room_id", "sender_id");

-- CreateIndex
CREATE INDEX "secrets_recipient_key_id_recipient_user_id_idx" ON "secrets"("recipient_key_id", "recipient_user_id");

-- CreateIndex
CREATE INDEX "secrets_sender_id_idx" ON "secrets"("sender_id");

-- CreateIndex
CREATE INDEX "secrets_active_expiry_idx" ON "secrets"("expires_at") WHERE (status = 'ACTIVE');

-- CreateIndex
CREATE UNIQUE INDEX "audit_events_id_key" ON "audit_events"("id");

-- CreateIndex
CREATE INDEX "audit_events_room_id_seq_idx" ON "audit_events"("room_id", "seq");

-- CreateIndex
CREATE INDEX "audit_events_actor_user_id_seq_idx" ON "audit_events"("actor_user_id", "seq");

-- CreateIndex
CREATE INDEX "audit_events_occurred_at_idx" ON "audit_events"("occurred_at");

-- AddForeignKey
ALTER TABLE "recovery_codes" ADD CONSTRAINT "recovery_codes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "login_attempts" ADD CONSTRAINT "login_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "user_key_pairs" ADD CONSTRAINT "user_key_pairs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_added_by_id_fkey" FOREIGN KEY ("added_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_removed_by_id_fkey" FOREIGN KEY ("removed_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_invitation_id_room_id_fkey" FOREIGN KEY ("invitation_id", "room_id") REFERENCES "invitations"("id", "room_id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invitee_user_id_fkey" FOREIGN KEY ("invitee_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invitee_key_id_invitee_user_id_fkey" FOREIGN KEY ("invitee_key_id", "invitee_user_id") REFERENCES "user_key_pairs"("id", "user_id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invited_by_id_fkey" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_approved_by_id_fkey" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_key_versions" ADD CONSTRAINT "room_key_versions_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_key_versions" ADD CONSTRAINT "room_key_versions_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "room_key_versions" ADD CONSTRAINT "room_key_versions_created_by_operation_id_fkey" FOREIGN KEY ("created_by_operation_id") REFERENCES "rekey_operations"("id") ON DELETE SET NULL ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "rekey_operations" ADD CONSTRAINT "rekey_operations_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "rekey_operations" ADD CONSTRAINT "rekey_operations_started_by_id_fkey" FOREIGN KEY ("started_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "key_envelopes" ADD CONSTRAINT "key_envelopes_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "key_envelopes" ADD CONSTRAINT "key_envelopes_room_id_key_version_fkey" FOREIGN KEY ("room_id", "key_version") REFERENCES "room_key_versions"("room_id", "version") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "key_envelopes" ADD CONSTRAINT "key_envelopes_recipient_key_id_recipient_user_id_fkey" FOREIGN KEY ("recipient_key_id", "recipient_user_id") REFERENCES "user_key_pairs"("id", "user_id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "key_envelopes" ADD CONSTRAINT "key_envelopes_invitation_id_room_id_fkey" FOREIGN KEY ("invitation_id", "room_id") REFERENCES "invitations"("id", "room_id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "key_envelopes" ADD CONSTRAINT "key_envelopes_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_files" ADD CONSTRAINT "encrypted_files_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_files" ADD CONSTRAINT "encrypted_files_room_id_key_version_fkey" FOREIGN KEY ("room_id", "key_version") REFERENCES "room_key_versions"("room_id", "version") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_files" ADD CONSTRAINT "encrypted_files_uploader_id_fkey" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_notes" ADD CONSTRAINT "encrypted_notes_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_notes" ADD CONSTRAINT "encrypted_notes_room_id_key_version_fkey" FOREIGN KEY ("room_id", "key_version") REFERENCES "room_key_versions"("room_id", "version") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_notes" ADD CONSTRAINT "encrypted_notes_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "encrypted_notes" ADD CONSTRAINT "encrypted_notes_updated_by_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "secrets" ADD CONSTRAINT "secrets_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "secrets" ADD CONSTRAINT "secrets_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "secrets" ADD CONSTRAINT "secrets_recipient_key_id_recipient_user_id_fkey" FOREIGN KEY ("recipient_key_id", "recipient_user_id") REFERENCES "user_key_pairs"("id", "user_id") ON DELETE RESTRICT ON UPDATE RESTRICT;
