import {
  changeVaultPassphrase,
  computeFingerprint,
  createVault,
  createWorkerRunner,
  formatFingerprint,
  isBelowKdfTarget,
  isDerivationRunning,
  publicIdentityFromWire,
  rewrapToWire,
  unlockVault,
  upgradeVaultProtection,
  vaultRecordFromWire,
  vaultRecordToWire,
  verifyPublicIdentity,
  type UnlockedVault,
  type VaultRecord,
} from '@ciphermesh/crypto';
import {
  directoryEntrySchema,
  sessionInfoResponseSchema,
  statusOkResponseSchema,
  vaultCreatedResponseSchema,
  vaultResetResponseSchema,
  vaultResponseSchema,
  vaultRewrapResponseSchema,
  type SessionInfoResponse,
} from '@ciphermesh/validation';
import { api, ApiError, onUnauthenticated } from '../lib/api';

/**
 * The vault in this tab (DF-03, DF-04, CP-22). All cryptography is done by @ciphermesh/crypto; this
 * controller only sequences it with the API and owns the in-memory state.
 *
 * Memory: the unlocked private keys are non-extractable CryptoKey handles held in a private field.
 * They are never put into React state, browser storage, cookies, URLs or the DOM, and nothing in
 * this module writes to localStorage, sessionStorage, IndexedDB or the Cache API (INV-01). Locking
 * drops every reference; JavaScript cannot guarantee that memory is wiped (L-15).
 *
 * Locking happens on: the "Lock now" action; 15 minutes without trusted user input (keyboard,
 * pointer or touch events generated by the user; script-generated events are ignored); the page
 * being hidden for back/forward caching or closed (pagehide); logout; and any API answer that the
 * session is gone (expiry, revocation, account disabled). A lock that becomes due while a vault
 * operation is running waits for it, then happens immediately; operations check after every await
 * whether the vault was locked meanwhile and discard their result if so.
 */
export const AUTO_LOCK_MS = 15 * 60_000;
const CHECK_INTERVAL_MS = 15_000;
const SESSION_CHECK_MS = 60_000;

export type LockReason = 'manual' | 'inactivity' | 'logout' | 'session-ended' | 'page-hidden' | 'identity-changed';

export interface AccountView {
  readonly userId: string;
  readonly email: string;
  readonly displayName: string;
  readonly mfaEnabled: boolean;
  readonly stepUpAt: string | null;
}

export interface IdentityView {
  readonly keyId: string;
  /** Computed in this browser from the public keys, after verifying the binding signature. */
  readonly fingerprint: string;
  readonly fingerprintGroups: readonly string[];
  readonly createdAt: string;
  readonly rewrappedAt: string | null;
  readonly kdf: { readonly memoryKiB: number; readonly iterations: number; readonly parallelism: number };
  readonly upgradeAvailable: boolean;
}

export type VaultView =
  | { readonly kind: 'loading' }
  | { readonly kind: 'signed-out' }
  | { readonly kind: 'failed'; readonly code: string }
  | { readonly kind: 'not-configured'; readonly account: AccountView }
  | {
      readonly kind: 'locked';
      readonly account: AccountView;
      readonly identity: IdentityView;
      readonly lockReason: LockReason | undefined;
    }
  | {
      readonly kind: 'unlocked';
      readonly account: AccountView;
      readonly identity: IdentityView;
      readonly lockAt: number;
    };

export interface DirectoryResult {
  readonly displayName: string;
  readonly accountCreatedAt: string;
  readonly keyId: string;
  readonly keyCreatedAt: string;
  /** Recomputed in this browser after verifying the identity's binding signature. */
  readonly fingerprintGroups: readonly string[];
}

/** Thrown when the server requires a fresh step-up before a vault change. */
export class StepUpRequired extends Error {
  constructor(readonly strict: boolean) {
    super('A recent confirmation of the account is required');
    this.name = 'StepUpRequired';
  }
}

const accountOf = (info: SessionInfoResponse): AccountView => ({
  userId: info.user.id,
  email: info.user.email,
  displayName: info.user.displayName,
  mfaEnabled: info.user.mfaEnabled,
  stepUpAt: info.session.stepUpAt,
});

async function identityViewOf(
  record: VaultRecord,
  createdAt: string,
  rewrappedAt: string | null,
): Promise<IdentityView> {
  // The public identity is verified, and its fingerprint recomputed, before anything is shown.
  const verified = await verifyPublicIdentity(record.identity);
  const fingerprint = await computeFingerprint(verified.encryptionKeySpki, verified.signingKeySpki);
  const kdf = {
    memoryKiB: record.kdf.memoryKiB,
    iterations: record.kdf.iterations,
    parallelism: record.kdf.parallelism,
  };
  return {
    keyId: verified.keyId,
    fingerprint,
    fingerprintGroups: formatFingerprint(fingerprint),
    createdAt,
    rewrappedAt,
    kdf,
    upgradeAvailable: isBelowKdfTarget(kdf),
  };
}

const STEP_UP_WINDOW_MS = { standard: 15 * 60_000, strict: 5 * 60_000 } as const;
const LOADING: VaultView = Object.freeze({ kind: 'loading' });

export class VaultController {
  #view: VaultView = LOADING;
  readonly #listeners = new Set<() => void>();
  /** Unlocked private keys. Never exposed; replaced only by a successful unlock or re-wrap. */
  #unlocked: UnlockedVault | undefined;
  /** Incremented on every lock: work that started before a lock discards its result. */
  #generation = 0;
  #busy = 0;
  #pendingLock: LockReason | undefined;
  #lastActivity = 0;
  #activitySinceSessionCheck = false;
  #started = false;
  #timers: ReturnType<typeof setInterval>[] = [];

  // ------------------------------------------------------------------ React subscription
  readonly subscribe = (listener: () => void): (() => void) => {
    this.#listeners.add(listener);
    return () => this.#listeners.delete(listener);
  };
  readonly getSnapshot = (): VaultView => this.#view;
  readonly getServerSnapshot = (): VaultView => LOADING;

  #set(view: VaultView): void {
    // The private keys exist only while the view is 'unlocked'. Every other view drops them, so no
    // state (for example an error view) can hold keys in memory outside the auto-lock (CP-22).
    if (view.kind !== 'unlocked') this.#unlocked = undefined;
    this.#view = view;
    for (const listener of this.#listeners) listener();
  }

  // ------------------------------------------------------------------ lifecycle and auto-lock
  /** Installs the auto-lock listeners once per page. Safe to call repeatedly. */
  start(): void {
    if (this.#started || typeof window === 'undefined') return;
    this.#started = true;
    this.#lastActivity = performance.now();
    const activity = (event: Event): void => {
      // Script-generated events are not user activity and cannot keep the vault open.
      if (!event.isTrusted) return;
      this.#lastActivity = performance.now();
      this.#activitySinceSessionCheck = true;
    };
    for (const type of ['keydown', 'pointerdown', 'touchstart']) {
      window.addEventListener(type, activity, { capture: true, passive: true });
    }
    // Leaving the page (closing, navigating away, entering the back/forward cache) locks, so an
    // unlocked vault is never restored from the cache.
    window.addEventListener('pagehide', () => {
      this.lock('page-hidden');
    });
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'visible') this.#checkInactivity();
    });
    this.#timers.push(
      setInterval(() => {
        this.#checkInactivity();
      }, CHECK_INTERVAL_MS),
    );
    this.#timers.push(
      setInterval(() => {
        void this.#checkSession();
      }, SESSION_CHECK_MS),
    );
    onUnauthenticated(() => {
      this.lock('session-ended');
      this.#unlocked = undefined;
      this.#set({ kind: 'signed-out' });
    });
  }

  #checkInactivity(): void {
    if (this.#view.kind !== 'unlocked') return;
    if (performance.now() - this.#lastActivity >= AUTO_LOCK_MS) this.lock('inactivity');
  }

  /**
   * While unlocked, confirms the session about once a minute, but only after real user activity,
   * so the check never keeps an idle session alive. A revoked or expired session, or a disabled
   * account, makes the API answer 401, which locks the vault (onUnauthenticated).
   */
  async #checkSession(): Promise<void> {
    if (this.#view.kind !== 'unlocked' || !this.#activitySinceSessionCheck) return;
    this.#activitySinceSessionCheck = false;
    try {
      await api('GET', '/auth/session', sessionInfoResponseSchema);
    } catch {
      // A 401 already locked the vault through onUnauthenticated; other errors are transient.
    }
  }

  /** Remaining time before the inactivity lock, for the header countdown. */
  millisecondsUntilAutoLock(): number {
    return Math.max(0, AUTO_LOCK_MS - (performance.now() - this.#lastActivity));
  }

  /**
   * Locks: drops the private keys, and invalidates any running operation. If an operation is in
   * flight (a derivation or an upload), the lock is applied as soon as it ends.
   */
  lock(reason: LockReason): void {
    if (this.#busy > 0 || isDerivationRunning()) {
      this.#pendingLock = reason;
      this.#generation += 1;
      return;
    }
    this.#applyLock(reason);
  }

  #applyLock(reason: LockReason): void {
    this.#generation += 1;
    this.#pendingLock = undefined;
    this.#unlocked = undefined;
    const view = this.#view;
    if (view.kind === 'unlocked') {
      this.#set({ kind: 'locked', account: view.account, identity: view.identity, lockReason: reason });
    }
  }

  async #run<T>(task: (generation: number) => Promise<T>): Promise<T> {
    this.#busy += 1;
    const generation = this.#generation;
    try {
      return await task(generation);
    } finally {
      this.#busy -= 1;
      if (this.#busy === 0 && this.#pendingLock !== undefined) this.#applyLock(this.#pendingLock);
      // A lock during the operation discarded its local result; show what the server now holds.
      if (!this.#current(generation)) void this.refresh();
    }
  }

  #current(generation: number): boolean {
    return generation === this.#generation;
  }

  // ------------------------------------------------------------------ loading
  /** Loads the account and the vault record. Never unlocks anything. */
  async refresh(): Promise<void> {
    try {
      const info = await api('GET', '/auth/session', sessionInfoResponseSchema);
      const account = accountOf(info);
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) {
        this.#unlocked = undefined;
        this.#set({ kind: 'not-configured', account });
        return;
      }
      const identity = await identityViewOf(loaded.record, loaded.createdAt, loaded.rewrappedAt);
      if (this.#view.kind === 'unlocked' && this.#unlocked?.identity.fingerprint === identity.fingerprint) {
        this.#set({ ...this.#view, account, identity });
        return;
      }
      // A different identity on the server (for example a reset on another device) locks this tab.
      // A vault that is already locked keeps its reason while the identity is the same, so a later
      // refresh (navigation, an operation finishing) never hides why it locked.
      const view = this.#view;
      const reason: LockReason | undefined =
        this.#unlocked !== undefined
          ? 'identity-changed'
          : view.kind === 'locked' && view.identity.fingerprint === identity.fingerprint
            ? view.lockReason
            : undefined;
      this.#set({ kind: 'locked', account, identity, lockReason: reason });
    } catch (error) {
      if (error instanceof ApiError && error.code === 'UNAUTHENTICATED') {
        this.#set({ kind: 'signed-out' });
        return;
      }
      // A transient failure (network, rate limit) while unlocked changes nothing: the keys still
      // belong to the identity loaded before, and the auto-lock keeps running. An error view
      // would drop them, and the next refresh would report a false identity change.
      if (this.#view.kind === 'unlocked') return;
      this.#set({ kind: 'failed', code: codeOf(error) });
    }
  }

  async #fetchRecord(
    userId: string,
  ): Promise<{ record: VaultRecord; createdAt: string; rewrappedAt: string | null } | undefined> {
    try {
      const response = await api('GET', '/vault', vaultResponseSchema);
      return {
        record: vaultRecordFromWire(response.vault, userId),
        createdAt: response.createdAt,
        rewrappedAt: response.rewrappedAt,
      };
    } catch (error) {
      if (error instanceof ApiError && error.code === 'VAULT_NOT_FOUND') return undefined;
      throw error;
    }
  }

  #account(): AccountView {
    const view = this.#view;
    if (view.kind === 'not-configured' || view.kind === 'locked' || view.kind === 'unlocked') return view.account;
    throw new ApiError(401, 'UNAUTHENTICATED', 'Authentication required');
  }

  #requireStepUp(window: 'standard' | 'strict'): void {
    const at = this.#account().stepUpAt;
    if (at === null || Date.now() - new Date(at).getTime() > STEP_UP_WINDOW_MS[window] - 30_000) {
      throw new StepUpRequired(window === 'strict');
    }
  }

  async #becomeUnlocked(generation: number, unlocked: UnlockedVault): Promise<void> {
    const account = this.#account();
    const loaded = await this.#fetchRecord(account.userId);
    if (loaded === undefined || !this.#current(generation)) return;
    const identity = await identityViewOf(loaded.record, loaded.createdAt, loaded.rewrappedAt);
    if (!this.#current(generation) || identity.fingerprint !== unlocked.identity.fingerprint) return;
    this.#unlocked = unlocked;
    this.#lastActivity = performance.now();
    this.#set({ kind: 'unlocked', account, identity, lockAt: Date.now() + AUTO_LOCK_MS });
  }

  // ------------------------------------------------------------------ vault operations
  /**
   * First setup (DF-03): identity generation, Argon2id and wrapping happen in this browser; only
   * the public identity, the KDF metadata and the two ciphertexts are uploaded.
   */
  async setup(passphrase: string): Promise<void> {
    this.#requireStepUp('standard');
    const account = this.#account();
    await this.#run(async (generation) => {
      const setup = await createVault({
        userId: account.userId,
        passphrase,
        account: { email: account.email, displayName: account.displayName },
        runner: createWorkerRunner(),
      });
      await this.#post('/vault', vaultRecordToWire(setup.record), vaultCreatedResponseSchema);
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'The vault was not stored');
      const unlocked = await setup.complete(loaded.record);
      if (this.#current(generation)) await this.#becomeUnlocked(generation, unlocked);
    });
  }

  /** Unlock (DF-04). The record is fetched fresh; the passphrase never leaves this browser. */
  async unlock(passphrase: string): Promise<void> {
    const account = this.#account();
    await this.#run(async (generation) => {
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault has been set up yet');
      const unlocked = await unlockVault({
        record: loaded.record,
        userId: account.userId,
        passphrase,
        runner: createWorkerRunner(),
      });
      if (this.#current(generation)) await this.#becomeUnlocked(generation, unlocked);
    });
  }

  /** Vault Passphrase change (CM-T028): same identity, new salt and ciphertexts, signed request. */
  async changePassphrase(currentPassphrase: string, newPassphrase: string): Promise<void> {
    this.#requireStepUp('standard');
    const account = this.#account();
    await this.#run(async (generation) => {
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault has been set up yet');
      const rewrap = await changeVaultPassphrase({
        record: loaded.record,
        userId: account.userId,
        currentPassphrase,
        newPassphrase,
        account: { email: account.email, displayName: account.displayName },
        runner: createWorkerRunner(),
      });
      await this.#post('/vault/rewrap', rewrapToWire(rewrap.request), vaultRewrapResponseSchema);
      const stored = await this.#fetchRecord(account.userId);
      if (stored === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault has been set up yet');
      const unlocked = await rewrap.complete(stored.record);
      if (this.#current(generation)) await this.#becomeUnlocked(generation, unlocked);
    });
  }

  /** Re-wraps with the same passphrase under the current Argon2id target (ADR-010). */
  async upgradeProtection(passphrase: string): Promise<void> {
    this.#requireStepUp('standard');
    const account = this.#account();
    await this.#run(async (generation) => {
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault has been set up yet');
      const upgrade = await upgradeVaultProtection({
        record: loaded.record,
        userId: account.userId,
        passphrase,
        runner: createWorkerRunner(),
      });
      await this.#post('/vault/rewrap', rewrapToWire(upgrade.request), vaultRewrapResponseSchema);
      const stored = await this.#fetchRecord(account.userId);
      if (stored === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault has been set up yet');
      const unlocked = await upgrade.complete(stored.record);
      if (this.#current(generation)) await this.#becomeUnlocked(generation, unlocked);
    });
  }

  /**
   * Vault reset after a lost passphrase: a NEW identity replaces the old one. Nothing protected
   * by the old private keys can be recovered by CipherMesh; there is no escrow or master key.
   */
  async reset(newPassphrase: string): Promise<void> {
    this.#requireStepUp('strict');
    const account = this.#account();
    const view = this.#view;
    if (view.kind !== 'locked' && view.kind !== 'unlocked') throw new ApiError(404, 'VAULT_NOT_FOUND', 'No vault');
    const supersedesKeyId = view.identity.keyId;
    this.lock('manual');
    await this.#run(async (generation) => {
      const setup = await createVault({
        userId: account.userId,
        passphrase: newPassphrase,
        account: { email: account.email, displayName: account.displayName },
        runner: createWorkerRunner(),
      });
      await this.#post(
        '/vault/reset',
        { supersedesKeyId, vault: vaultRecordToWire(setup.record) },
        vaultResetResponseSchema,
      );
      const loaded = await this.#fetchRecord(account.userId);
      if (loaded === undefined) throw new ApiError(404, 'VAULT_NOT_FOUND', 'The vault was not stored');
      const unlocked = await setup.complete(loaded.record);
      if (this.#current(generation)) await this.#becomeUnlocked(generation, unlocked);
    });
  }

  /** Public-key directory lookup (CM-T027). The returned identity is verified here, not trusted. */
  async lookup(email: string): Promise<DirectoryResult> {
    const entry = await api('POST', '/directory/lookup', directoryEntrySchema, { email });
    const identity = await verifyPublicIdentity(publicIdentityFromWire(entry.identity, entry.user.id));
    const fingerprint = await computeFingerprint(identity.encryptionKeySpki, identity.signingKeySpki);
    return {
      displayName: entry.user.displayName,
      accountCreatedAt: entry.user.accountCreatedAt,
      keyId: identity.keyId,
      keyCreatedAt: entry.identity.createdAt,
      fingerprintGroups: formatFingerprint(fingerprint),
    };
  }

  /** Logout: lock first, then end the server session (session-and-csrf.md section 5). */
  async logout(): Promise<void> {
    this.lock('logout');
    try {
      await api('POST', '/auth/logout', statusOkResponseSchema);
    } finally {
      this.#unlocked = undefined;
      this.#set({ kind: 'signed-out' });
    }
  }

  /** Marks a step-up done in this tab (the server is the authority; this only avoids a round trip). */
  async noteStepUp(): Promise<void> {
    await this.refresh();
  }

  async #post<S extends Parameters<typeof api>[2]>(path: string, body: unknown, schema: S) {
    try {
      return await api('POST', path, schema, body);
    } catch (error) {
      if (error instanceof ApiError && error.code === 'STEP_UP_REQUIRED')
        throw new StepUpRequired(path === '/vault/reset');
      throw error;
    }
  }
}

/** A stable code for any error, for messages; never the error text itself. */
export function codeOf(error: unknown): string {
  if (error instanceof StepUpRequired) return 'STEP_UP_REQUIRED';
  if (error instanceof ApiError) return error.code;
  if (typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string')
    return error.code;
  return 'UNKNOWN';
}

/** The vault of this tab. */
export const vaultController = new VaultController();
